name:                dirforest
version:             0.0.0.0
github:              "NorfairKing/dirforest"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - containers
  - deepseq
  - filepath
  - path
  - path-io
  - validity
  - validity-containers
  - validity-path
