name: dirforest
version: 0.1.0.0
github: "NorfairKing/dirforest"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2020-2023 Tom Sydney Kerckhove"
synopsis: Typed directory forest
license: MIT

extra-source-files:
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec
  - containers
  - deepseq
  - filepath
  - path
  - path-io
  - validity
  - validity-containers
  - validity-path
