name: genvalidity-dirforest
version: 0.1.0.1
github: "NorfairKing/dirforest"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-ysd.eu"
copyright: "2020-2023 Tom Sydney Kerckhove"
synopsis: Generators for typed directory forests
license: MIT

extra-source-files:
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - containers
  - dirforest
  - filepath
  - genvalidity >=1.0.0.0
  - genvalidity-containers
  - genvalidity-path
  - path

tests:
  dirforest-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - dirforest
    - filepath
    - genvalidity-bytestring
    - genvalidity-dirforest
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - sydtest
    - path
    - path-io

benchmarks:
  dirforest-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - criterion
    - genvalidity
    - dirforest
    - genvalidity-dirforest
    - genvalidity-criterion
    - genvalidity-text
