name:                genvalidity-dirforest
version:             0.0.0.0
github:              "NorfairKing/dirforest"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-ysd.eu"
copyright:           "2020 Tom Sydney Kerckhove"


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - containers
  - dirforest
  - filepath
  - genvalidity
  - genvalidity-containers
  - genvalidity-path
  - path

tests:
  dirforest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - dirforest
    - genvalidity-bytestring
    - genvalidity-dirforest
    - genvalidity-hspec
    - hspec
    - path
    - path-io
