resolver: lts-23.19
packages:
- dirforest
- genvalidity-dirforest
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wcompat

system-ghc: true
nix:
  enable: false
with-hpack: hpack
