resolver: lts-19.32
packages:
- dirforest
- genvalidity-dirforest
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wcompat
extra-deps:
  - github: NorfairKing/autodocodec
    commit: dde958c53fffe86f0c43dc1c530df3cf73361d6a
    subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

  - github: NorfairKing/safe-coloured-text
    commit: f18578151d579c495eda46b8eeafcddb69adea07
    subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

  - github: NorfairKing/sydtest
    commit: 2375dbc3b8cc34788dca2baea779f148c173f5b0
    subdirs:
    - sydtest
    - sydtest-discover

  - github: NorfairKing/validity
    commit: a251897dc1eb7e851fd4d3dbc6fa976d22388f27
    subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector

system-ghc: true
nix:
  enable: false
with-hpack: hpack
